# Generated by Django 2.1.7 on 2019-02-25 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField(choices=[(5, '5%'), (7, '7%'), (12, '12%'), (30, '30%'), (50, '50%'), (70, '70%')])),
                ('plan', models.PositiveSmallIntegerField(choices=[(1, 'Plan 1'), (2, 'Plan 2'), (3, 'Plan 3')])),
                ('is_trial', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_limited', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('expire_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_users', to='user_api.AdminUser')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_users', to='user_api.MainUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreKeeperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='user_api.AdminUser')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='user_api.MainUser')),
                ('manager_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='user_api.ManagerUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_user', models.BooleanField()),
                ('is_admin_user', models.BooleanField()),
                ('is_manager_user', models.BooleanField()),
                ('is_store_keeper_user', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='main_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='user_api.MainUser'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
