# Generated by Django 2.1.7 on 2019-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='discount',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (7, '7%'), (12, '12%'), (30, '30%'), (50, '50%'), (70, '70%')]),
        ),
    ]
