# Generated by Django 2.1.7 on 2019-02-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_auto_20190226_1556'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
            ],
        ),
    ]
