"""
Django settings for src src.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from project.core.settings.application_defination import INSTALLED_APPS
from project.core.settings.middlewere import MIDDLEWARE
from project.core.settings.template import TEMPLATES
from project.core.settings.database import DEVELOPMENT_DATABASE
from project.core.settings.password_validator import AUTH_PASSWORD_VALIDATORS
from project.core.settings.password_hasher import PASSWORD_HASHERS
from project.core.settings.static import *

# Application definition

INSTALLED_APPS = INSTALLED_APPS

MIDDLEWARE = MIDDLEWARE

TEMPLATES = TEMPLATES


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = DEVELOPMENT_DATABASE


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

PASSWORD_HASHERS = PASSWORD_HASHERS

AUTH_PASSWORD_VALIDATORS = AUTH_PASSWORD_VALIDATORS


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = STATIC_URL

""" CORS HEADERS CONFIGURATIONS """

CORS_ORIGIN_WHITELIST = (
    'localhost',
)
