# Generated by Django 2.1.7 on 2019-02-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0002_auto_20190225_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='user_api.MainUser')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryManagerConnectionBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='inventory.Inventory')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_connections', to='user_api.MainUser')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='user_api.ManagerUser')),
            ],
        ),
    ]
